version: '0.1.0'

services:
  app:
    container_name: app
    image: app_image
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/home/root/app
    ports:
      - "8000:8000"
    depends_on:
      - app_db

  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:14.1
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app_front:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - default


volumes:
  app_pg_data:
    driver: "local"
