"""add_mapbox_uuid

Revision ID: dceb102ff5b2
Revises: a45ec762943b
Create Date: 2023-05-23 05:24:57.250285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dceb102ff5b2'
down_revision = 'a45ec762943b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geojson_data', sa.Column('mapbox_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geojson_data', 'mapbox_uuid')
    # ### end Alembic commands ###
