"""

Revision ID: a45ec762943b
Revises: 19e85778574d
Create Date: 2023-05-22 18:16:17.807534

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a45ec762943b'
down_revision = '19e85778574d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geojson_data',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=42, cycle=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('geojson_data_pkey'))
    )
    # op.create_index(op.f('iss_data_timestamp_idx'), 'iss_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    #### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('iss_data_timestamp_idx'), table_name='iss_data')
    op.drop_table('geojson_data')
    #### end Alembic commands ###
