"""iss_data_table

Revision ID: 19e85778574d
Revises: 
Create Date: 2023-05-19 09:15:36.966907

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '19e85778574d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iss_data',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('footprint', sa.Float(), nullable=False),
    sa.Column('daynum', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('solar_lat', sa.Float(), nullable=False),
    sa.Column('solar_lon', sa.Float(), nullable=False),
    sa.Column('units', sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iss_data')
    # ### end Alembic commands ###
